- hosts: 192.168.56.10
  remote_user: vagrant

  become: true
  
  tasks:
    - name: copy script to /root/
      copy:
          src: main.sh
          dest: /root/main.sh
          mode: 0700
          
    - name: copy ansible main to /root/
      copy:
          src: main.yml
          dest: /root/main.yml

    - name: Set default time to shutdown computers at Midday
      cron: name=script_exec minute=*/30 state=present job="flock -n /root/updater /root/main.sh"